<?php
include('../session.php');
include("../connect.php");
include("../converter.php");

if(isset($_GET['pur_No'])){
  $sale_No = $_GET['pur_No'];
  $result1 = mysqli_query($con,"SELECT * FROM pcounter WHERE id='$sale_No'");
  $fetch1 = mysqli_fetch_array($result1);
  $day = $fetch1['sale_day']; 
  $customer = $fetch1['customer'];
  $result2  = mysqli_query($con,"SELECT * FROM accounts WHERE id='$customer'");
  $fetch2 = mysqli_fetch_array($result2);
  $result3 = mysqli_query($con,"SELECT * FROM pcounter WHERE id='$sale_No'");
  $fetch3 = mysqli_fetch_array($result3);
}
date_default_timezone_set("Asia/Karachi");
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Purchase Invoice Print</title>
  <link href="../assets/css/font-awesome.css" rel="stylesheet" />
  <style type="text/css">
  .mainTable {
    border-bottom: 1px solid black; 
    border-top: 1px solid black;
    text-align: left;
  }
</style>
</head>
<body>

<table width="100%">
  <tr>
    <td>
       <center><h3 style="width: 300px;"><u>
      <?php 
        $result4 = mysqli_query($con,"SELECT * FROM company");
        $fetch4 = mysqli_fetch_array($result4);
        echo $fetch4['name'];
      ?>
       </u></h3><i class="fa fa-phone" aria-hidden="true" style="margin-top: -10px;">  <?php echo $fetch4['phone1'] ?></i></center>
    </td>
  </tr>
</table>
<table width="100%">
  <tr>
    <td>Order #: <?php echo $sale_No; ?></td>
    <td style="text-align:right;">Date: <?php echo date("d/m/Y", strtotime($day)); ?></td>
  </tr>
  <tr>
    <td>Customer: <?php echo $fetch2['name']." (".$fetch3['transport_By'].")"; ?></td>
    <td style="text-align:right;">Time: <?php echo date("h:iA"); ?></td>
  </tr>
  <tr>
    <td>Address: <?php echo $fetch2['address']; ?></td>
  </tr>
</table>
<center><h3><u><em>Order Invoice</em></u></h3></center>
<table class="main" border="0" width="100%" cellpadding="0" cellspacing="0" style="font-size: 14px;">
  <tr>
   <th class="mainTable">Sr#</th>
   <th class="mainTable">Product Name</th>
   <th class="mainTable">Qty</th>
   <th class="mainTable">price</th>  
   <th class="mainTable">Final</th>
  </tr>
 <?php
  $total1 = $dis = $received = $remaining = $finalValue = $counter = $itemDiscount = $totalQty = $finalValue= 0;
  $result5 = mysqli_query($con,"SELECT * FROM psale WHERE sale_No ='$sale_No'");
  while($fetch5=mysqli_fetch_array($result5)){$counter++;?>
 <tr>
  <td><?php echo $counter;?> </td>
  <td><?php echo getProductName($fetch5['barcode']);?> </td>
  <td><?php echo $fetch5['qty'];?></td>
  <td><?php echo $fetch5['price'];?></td>
  <td><?php echo $fetch5['qty']*$fetch5['price']; ?></td>
 </tr>
  <?php 
    $dis = $fetch5['discount'];
    $total1 = $fetch5['grossId'];
    $finalValue = $fetch5['finalValue'];
    $received = $fetch5['received']+0;
    $remaining = $fetch5['remaining']+0;
  } ?>
  <tr>
   <td style="border-top: 1px solid black;" colspan="5"></td>
 </tr>
</table>
<table cellpadding="0" border="0" cellspacing="0" style="margin-top: 6px;" >
  <tr>
    <td>Gross Amount: </td>
    <td>&nbsp;<?php echo $total1; ?></td>
  </tr>
  <tr>
    <td>Disc:</td>
    <td>&nbsp;<?php echo $dis; ?></td>
  </tr>
  <tr>
    <td>Final Amount:</td>
    <td>&nbsp;<?php echo $finalValue; ?></td>
  </tr>
  <tr>
    <td>Advance:</td>
    <td>&nbsp;<?php echo $received; ?></td>
  </tr>
  <tr>
    <td>Remaining:</td>
    <td>&nbsp;<?php echo $remaining; ?></td>
  </tr>
</table>
<br><br>
<table class="main" border="0" width="100%" cellpadding="0" cellspacing="0" style="font-size: 17px;text-align: center;">
  <tr>
    <td><?php echo $_SESSION['name']; ?><br><span style="margin-top:-10px">______________________</span></td>
    <td><br>______________________</td>
    <td><br>______________________</td>
  </tr>
  <tr>
    <td>Generated By</td>
    <td>Approved By</td>
    <td>Approved By Owner</td>
  </tr>
</table>
</body>
</html>