<title>Trial Balance By Head</title>
<?php 
include("../header.php"); include('../connect.php'); include('function.php');
?>
<style type="text/css">
	.important {
		color: red;
	}
</style>
<center><h1>Trial Balance By Head</h1></center><hr>
<form method="POST" id="lockForm">
<div class="container">
<div class="row">
	<div class="col-md-3">
		<label>Type<span class="important">*</span></label>
		<select class="form-control" name="product">
			<option disabled selected>--- Select ---</option>
			<?php 
				$result = mysqli_query($con,"SELECT * FROM accounts WHERE active!='0' GROUP BY type");
				while ($fetch=mysqli_fetch_array($result)) {
					echo "<option value=".$fetch['type'].">".$fetch['type']."</option>";
				}
			?>
		</select>
	</div>

	<div class="col-md-3">
		<label>From Date</label>
		<input type="date" id="vendorId" name="fromDate" class="form-control" value="<?php echo date('Y-m-d'); ?>" required readonly>
		<input type="submit" id="submit-hidden" style="display: none;">
	</div>
	<div class="col-md-3">
		<label>To Date</label>
		<input type="date" class="form-control" name="toDate" value="<?php echo date('Y-m-d'); ?>" required readonly><br>
	</div>
</div>
</form>
<div class="row">
	<div class="col-md-4">
		<input type="button" class="btn btn-primary" onclick="getReport()" value="Show Report" />
		<input type="button" class="btn btn-info" onclick="printDiv('printableArea')" value="Print" accesskey="p" />
	</div>
</div>
</div>
<hr>
<div id="printableArea">
<div class="row container-fluid">
	<table width="100%" border="0">
		<?php 
			$result = mysqli_query($con,"SELECT * FROM company");
			$fetch = mysqli_fetch_array($result);
		?>
		<tr>
			<td colspan="3" style="text-align: center;font-size: 20px;padding-bottom: 5px;"><i><?php echo $fetch['name'] ?></i></td>
		</tr>
		<tr>
			<td colspan="3" style="text-align: center;font-size: 25px;">Trial Balance By Head</td>
		</tr>
		<tr>
			<td colspan="2">Generated By:&nbsp;<u>Admin</u></td>
			<td style="text-align: right;padding-top: 5px;">From:&nbsp;<u id="from">N/A</u></td>
		</tr>
		<tr>
			<td colspan="2">Print Date: <u><?php date_default_timezone_set("Asia/Karachi"); echo date("d-m-Y h:i-a"); ?></u></td>
			<td style="text-align: right;padding-top: 5px;">To:&nbsp;<u id="to">N/A</u></td>
		</tr>
	</table><br>	
</div>
<div class="container-fluid">
<div class="row">
	<table border="1" class="table" id="myTable" width="100%">
		<thead>
			<tr>
				<th colspan="8" style="text-align: center;border-bottom: 1px solid black;" id="productName">N/A</th>
			</tr>
			<tr>
				<th>Sr#</th>
				<th>A/C#</th>
				<th>A/C Title</th>
				<th>Area/City</th>
				<th>Amount</th>
			</tr>
		</thead> 
		<tbody id="tableData"></tbody>
		<tfoot>
			<tr>
				<td colspan="5" style="text-align: center;font-size: 13px;"><i>© Arbaz Ehsan; 03137747660; arbazehsan988@gmail.com</i></td>
			</tr>
		</tfoot>
	</table>
</div>
</div>
</div>
<?php 
include("../footer.php");
?>
<script type="text/javascript">
function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
}

function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}

function getReport(argument) {
	if(!$("#lockForm")[0].checkValidity()){
		$("#lockForm").find("#submit-hidden").click();
	}
	else {
		var formData = new FormData($("#lockForm")[0]);
		$.ajax({
	        url: "operation.php?from=tbbh&operation=show",
	        type: 'POST',
	        data: formData,
	        async: false,
	        success: function (info) {
		 		// alert(info);
		 		var data = info.split("|"); 
		   		$("#tableData").html(data[0]);
		   		$("#from").html("All");
		   		$("#to").html("All");
		   		$("#productName").html(data[3]);
	        },
	        cache: false,
	        contentType: false,
	        processData: false
	    });
	}
}
</script>
