<?php 
include('../session.php');
include("../connect.php");

?>

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Cash Receipt Print</title>
  <link href="../assets/css/font-awesome.css" rel="stylesheet" />
  <style type="text/css">
    .mainTable {
      border-bottom: 1px solid black; 
      border-top: 1px solid black;
      text-align: left;
    }
  </style>
</head>
<body>

<div style="margin-top: 0px;">
  <table width="100%">
    <tr>
      <td>
        <center><h3 style="width: 300px;"><u>
        <?php 
          $result = mysqli_query($con,"SELECT * FROM company");
          $fetch = mysqli_fetch_array($result);
          echo $fetch['name'];
        ?>
         </u></h3><i class="fa fa-phone" aria-hidden="true" style="margin-top: -10px;">  <?php echo $fetch['phone1']; ?></i>
        </center>
      </td>
    </tr>
  </table>
</div>
<br><br>
<div>
<?php
 $sale_No = $_GET['sale_No'];
 $result2 = mysqli_query($con,"SELECT * FROM tcounter WHERE id='$sale_No'");
 $fetch2 = mysqli_fetch_array($result2);
 $sale_day = $fetch2['day'];
 ?>
</div>
<table border="0" style="text-align: left;" width="100%">
  <tr>
    <th>Invoice #: <?php echo $sale_No; ?></th>
    <th style="text-align: right;">Date: <?php echo date("d/m/Y", strtotime($sale_day)); ?></th>
  </tr>
  <tr>
    <th>Voucher #: <?php echo $fetch2['voucher_no']; ?></th>
    <th style="text-align: right;">Time: <?php date_default_timezone_set("Asia/Karachi"); echo date("h:iA");?></th>
  </tr>
</table>
<br>
<center><h4 style="margin-top: -22px;"><u><em>Cash Receipt</em></u></h4></center>
<table class="main" border="0" width="100%" cellpadding="0" cellspacing="0" style="font-size: 17px;">
  <tr>
    <th class="mainTable">Sr#</th> 
    <th class="mainTable">Remarks</th> 
    <th class="mainTable">Received By</th>
    <th class="mainTable">Amount Received</th>
  </tr>
  <?php
  $result3 = mysqli_query($con,"SELECT * FROM trans WHERE bill_no='$sale_No'");
  $counter = $amntPaid = $remaining = 0;
  while($fetch3=mysqli_fetch_array($result3)){ 
    $counter++; 
    $amntPaid += $fetch3['amount'];
    $result4 = mysqli_query($con,"SELECT * FROM accounts WHERE id = '".$fetch3['account_id']."'");
    $fetch4 = mysqli_fetch_array($result4);
  ?>
<tr>
  <td><?php echo $counter; ?></td> 
  <td><?php echo $fetch3['remarks'] ?></td> 
  <td><?php echo $fetch4['name'] ?></td>
  <td><?php echo $fetch3['amount'] ?></td>
</tr>
<?php } ?>
<tr>
   <td style="border-top: 1px solid black;" colspan="5"></td>
</tr>
</table>
<table class="main" border="0" width="100%" cellpadding="0" cellspacing="0" style="font-size: 17px;margin-top: 6px;">
  <tr>
    <td width="70%">Total items: <?php echo $counter;?></td>
    <td style="border-top:1px solid black;border-bottom:1px solid black;">Total: <?php echo $amntPaid; ?></td>
  </tr>
</table>
<br><br>
<table class="main" border="0" width="100%" cellpadding="0" cellspacing="0" style="font-size: 17px;text-align: center;">
  <tr>
    <td><?php echo $_SESSION['name']; ?><br><span style="margin-top:-10px">______________________</span></td>
    <td><br>______________________</td>
    <td><br>______________________</td>
  </tr>
  <tr>
    <td>Generated By</td>
    <td>Approved By</td>
    <td>Approved By Owner</td>
  </tr>
</table>
<br>
</body>
</html>