<title>Profit and Loss Report</title>
<?php 
include("../header.php"); include('../connect.php'); include('function.php');
?>
<style type="text/css">
	.important {
		color: red;
	}
</style>
<center><h1>Profit and Loss Report</h1></center><hr>
<form method="POST" id="lockForm">
<div class="container">
<div class="row">
	<!-- <div class="col-md-3">
		<label>Party</label>
		<select class="form-control" name="product">
			<option disabled selected>--- Select ---</option>
			<option>HTML</option>
			<option>PHP</option>
			<option>CSS</option>
		</select>
	</div> -->

	<div class="col-md-3">
		<label>From Date<span class="important">*</span></label>
		<input type="date" id="fromDate" name="fromDate" class="form-control" required>
		<input type="submit" id="submit-hidden" style="display: none;">
	</div>
	<div class="col-md-3">
		<label>To Date<span class="important">*</span></label>
		<input type="date" class="form-control" name="toDate" required><br>
	</div>
</div>
</form>
<div class="row">
	<div class="col-md-4">
		<input type="button" class="btn btn-primary" onclick="getReport()" value="Show Report" />
		<input type="button" class="btn btn-info" onclick="printDiv('printableArea')" value="Print" accesskey="p" />
	</div>
</div>
</div>
<hr>
<div id="printableArea">
<div class="container-fluid">
<div class="row">
	<table width="100%" border="0">
		<?php 
			$result = mysqli_query($con,"SELECT * FROM company");
			$fetch = mysqli_fetch_array($result);
		?>
		<tr>
			<td colspan="3" style="text-align: center;font-size: 20px;padding-bottom: 5px;"><i><?php echo $fetch['name'] ?></i></td>
		</tr> 
		<tr>
			<td colspan="3" style="text-align: center;font-size: 25px;">Profit and Loss Report</td>
		</tr>
		<tr>
			<td colspan="2">Generated By:&nbsp;<u>Admin</u></td>
			<td style="text-align: right;padding-top: 0px;">From:&nbsp;<u id="from">N/A</u></td>
		</tr>
		<tr>
			<td colspan="2">Print Date: <u><?php date_default_timezone_set("Asia/Karachi"); echo date("d-m-Y h:i-a"); ?></u></td>
			<td style="text-align: right;padding-top: 0px;">To:&nbsp;<u id="to">N/A</u></td>
		</tr>
	</table><br>	
</div>

<div class="row">
	<style type="text/css">
		tr td {
			padding: 5px;
			margin: 2px;
		}
		tr th {
			padding: 10px;
		}
		.bg-yellow {
			background: yellow;
			padding: 20px;
		}
		.align {
			text-align: right;
		}
		.align-center {
			text-align: center;
		}
		.border {
			border-bottom: 1px solid black;
			border-top: 1px solid black;
		}
		.font-bold {
			font-weight: bold;
		}
	</style>
	<table border="0" class="table" width="100%">
		<thead>
			<tr style="border-top: 1px solid black;">
				<th style="border-bottom: 1px solid black;">Particulars</th>
				<th class="border align" style="border-bottom: 1px solid black;">Qty</th>
				<th class="border align" style="border-bottom: 1px solid black;">Amount (Rs.)</th>
				<th class="border align" style="border-bottom: 1px solid black;">Avg. Price</th>
			</tr>
		</thead> 
		<tbody id="tableData"></tbody>
		<tfoot>
			<tr>
				<td colspan="7" style="text-align: center;font-size: 13px;"><i>© Arbaz Ehsan; 03137747660; arbazehsan988@gmail.com</i></td>
			</tr>
		</tfoot>
		<!-- <tfoot>
		<tr>
			<td colspan="6" style="text-align: right;"><b>Grand Total</b></td>
			<td style="border:2px solid black"><?php echo $sum; ?></td> 
		</tr>
		</tfoot> -->
	</table>
</div>
</div>
</div>
<?php 
include("../footer.php");
?>
<script type="text/javascript">
function printDiv(divName) {
     var printContents = document.getElementById(divName).innerHTML;
     var originalContents = document.body.innerHTML;
     document.body.innerHTML = printContents;
     window.print();
     document.body.innerHTML = originalContents;
}

function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}

function getReport(argument) {
	if(!$("#lockForm")[0].checkValidity()){
		$("#lockForm").find("#submit-hidden").click();
	}
	else {
		var formData = new FormData($("#lockForm")[0]);
		$.ajax({
	        url: "operation.php?from=palr&operation=show",
	        type: 'POST',
	        data: formData,
	        async: false,
	        success: function (info) {
		 		// alert(info);
		 		var data = info.split("|"); 
		   		$("#tableData").html(data[0]);
		   		$("#from").html(data[1]);
		   		$("#to").html(data[2]);
	        },
	        cache: false,
	        contentType: false,
	        processData: false
	    });
	}
}
</script>
